# docker-compose.yml
version: '3.8'

services:
  flavorlens-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MOTHERDUCK_TOKEN=${MOTHERDUCK_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
      - LOG_LEVEL=${LOG_LEVEL}
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]